// This file is auto-generated by @hey-api/openapi-ts

export type ActivityClubActivity = {
    athlete?: AthleteMetaAthlete;
    /**
     * The name of the activity
     */
    name?: string;
    /**
     * The activity's distance, in meters
     */
    distance?: number;
    /**
     * The activity's moving time, in seconds
     */
    moving_time?: number;
    /**
     * The activity's elapsed time, in seconds
     */
    elapsed_time?: number;
    /**
     * The activity's total elevation gain.
     */
    total_elevation_gain?: number;
    type?: ActivityTypeActivityType;
    sport_type?: SportTypeSportType;
    /**
     * The activity's workout type
     */
    workout_type?: number;
};

export type ActivityDetailedActivity = ActivitySummaryActivity & {
    /**
     * The description of the activity
     */
    description?: string;
    photos?: PhotoPhotosSummary;
    gear?: GearSummaryGear;
    /**
     * The number of kilocalories consumed during this activity
     */
    calories?: number;
    segment_efforts?: Array<SegmentEffortDetailedSegmentEffort>;
    /**
     * The name of the device used to record the activity
     */
    device_name?: string;
    /**
     * The token used to embed a Strava activity
     */
    embed_token?: string;
    /**
     * The splits of this activity in metric units (for runs)
     */
    splits_metric?: Array<SplitSplit>;
    /**
     * The splits of this activity in imperial units (for runs)
     */
    splits_standard?: Array<SplitSplit>;
    laps?: Array<LapLap>;
    best_efforts?: Array<SegmentEffortDetailedSegmentEffort>;
};

export type ActivityMetaActivity = {
    /**
     * The unique identifier of the activity
     */
    id?: number;
};

export type ActivitySummaryActivity = ActivityMetaActivity & {
    /**
     * The identifier provided at upload time
     */
    external_id?: string;
    /**
     * The identifier of the upload that resulted in this activity
     */
    upload_id?: number;
    athlete?: AthleteMetaAthlete;
    /**
     * The name of the activity
     */
    name?: string;
    /**
     * The activity's distance, in meters
     */
    distance?: number;
    /**
     * The activity's moving time, in seconds
     */
    moving_time?: number;
    /**
     * The activity's elapsed time, in seconds
     */
    elapsed_time?: number;
    /**
     * The activity's total elevation gain.
     */
    total_elevation_gain?: number;
    /**
     * The activity's highest elevation, in meters
     */
    elev_high?: number;
    /**
     * The activity's lowest elevation, in meters
     */
    elev_low?: number;
    type?: ActivityTypeActivityType;
    sport_type?: SportTypeSportType;
    /**
     * The time at which the activity was started.
     */
    start_date?: string;
    /**
     * The time at which the activity was started in the local timezone.
     */
    start_date_local?: string;
    /**
     * The timezone of the activity
     */
    timezone?: string;
    start_latlng?: LatlngLatLng;
    end_latlng?: LatlngLatLng;
    /**
     * The number of achievements gained during this activity
     */
    achievement_count?: number;
    /**
     * The number of kudos given for this activity
     */
    kudos_count?: number;
    /**
     * The number of comments for this activity
     */
    comment_count?: number;
    /**
     * The number of athletes for taking part in a group activity
     */
    athlete_count?: number;
    /**
     * The number of Instagram photos for this activity
     */
    photo_count?: number;
    /**
     * The number of Instagram and Strava photos for this activity
     */
    total_photo_count?: number;
    map?: MapPolylineMap;
    /**
     * Whether this activity was recorded on a training machine
     */
    trainer?: boolean;
    /**
     * Whether this activity is a commute
     */
    commute?: boolean;
    /**
     * Whether this activity was created manually
     */
    manual?: boolean;
    /**
     * Whether this activity is private
     */
    private?: boolean;
    /**
     * Whether this activity is flagged
     */
    flagged?: boolean;
    /**
     * The activity's workout type
     */
    workout_type?: number;
    /**
     * The unique identifier of the upload in string format
     */
    upload_id_str?: string;
    /**
     * The activity's average speed, in meters per second
     */
    average_speed?: number;
    /**
     * The activity's max speed, in meters per second
     */
    max_speed?: number;
    /**
     * Whether the logged-in athlete has kudoed this activity
     */
    has_kudoed?: boolean;
    /**
     * Whether the activity is muted
     */
    hide_from_home?: boolean;
    /**
     * The id of the gear for the activity
     */
    gear_id?: string;
    /**
     * The total work done in kilojoules during this activity. Rides only
     */
    kilojoules?: number;
    /**
     * Average power output in watts during this activity. Rides only
     */
    average_watts?: number;
    /**
     * Whether the watts are from a power meter, false if estimated
     */
    device_watts?: boolean;
    /**
     * Rides with power meter data only
     */
    max_watts?: number;
    /**
     * Similar to Normalized Power. Rides with power meter data only
     */
    weighted_average_watts?: number;
};

export type ActivityUpdatableActivity = {
    /**
     * Whether this activity is a commute
     */
    commute?: boolean;
    /**
     * Whether this activity was recorded on a training machine
     */
    trainer?: boolean;
    /**
     * Whether this activity is muted
     */
    hide_from_home?: boolean;
    /**
     * The description of the activity
     */
    description?: string;
    /**
     * The name of the activity
     */
    name?: string;
    type?: ActivityTypeActivityType;
    sport_type?: SportTypeSportType;
    /**
     * Identifier for the gear associated with the activity. ‘none’ clears gear from activity
     */
    gear_id?: string;
};

/**
 * A set of rolled-up statistics and totals for an athlete
 */
export type ActivityStatsActivityStats = {
    /**
     * The longest distance ridden by the athlete.
     */
    biggest_ride_distance?: number;
    /**
     * The highest climb ridden by the athlete.
     */
    biggest_climb_elevation_gain?: number;
    recent_ride_totals?: ActivityTotalActivityTotal;
    recent_run_totals?: ActivityTotalActivityTotal;
    recent_swim_totals?: ActivityTotalActivityTotal;
    ytd_ride_totals?: ActivityTotalActivityTotal;
    ytd_run_totals?: ActivityTotalActivityTotal;
    ytd_swim_totals?: ActivityTotalActivityTotal;
    all_ride_totals?: ActivityTotalActivityTotal;
    all_run_totals?: ActivityTotalActivityTotal;
    all_swim_totals?: ActivityTotalActivityTotal;
};

/**
 * A roll-up of metrics pertaining to a set of activities. Values are in seconds and meters.
 */
export type ActivityTotalActivityTotal = {
    /**
     * The number of activities considered in this total.
     */
    count?: number;
    /**
     * The total distance covered by the considered activities.
     */
    distance?: number;
    /**
     * The total moving time of the considered activities.
     */
    moving_time?: number;
    /**
     * The total elapsed time of the considered activities.
     */
    elapsed_time?: number;
    /**
     * The total elevation gain of the considered activities.
     */
    elevation_gain?: number;
    /**
     * The total number of achievements of the considered activities.
     */
    achievement_count?: number;
};

/**
 * An enumeration of the types an activity may have. Note that this enumeration does not include new sport types (e.g. MountainBikeRide, EMountainBikeRide), activities with these sport types will have the corresponding activity type (e.g. Ride for MountainBikeRide, EBikeRide for EMountainBikeRide)
 */
export type ActivityTypeActivityType = 'AlpineSki' | 'BackcountrySki' | 'Canoeing' | 'Crossfit' | 'EBikeRide' | 'Elliptical' | 'Golf' | 'Handcycle' | 'Hike' | 'IceSkate' | 'InlineSkate' | 'Kayaking' | 'Kitesurf' | 'NordicSki' | 'Ride' | 'RockClimbing' | 'RollerSki' | 'Rowing' | 'Run' | 'Sail' | 'Skateboard' | 'Snowboard' | 'Snowshoe' | 'Soccer' | 'StairStepper' | 'StandUpPaddling' | 'Surfing' | 'Swim' | 'Velomobile' | 'VirtualRide' | 'VirtualRun' | 'Walk' | 'WeightTraining' | 'Wheelchair' | 'Windsurf' | 'Workout' | 'Yoga';

export type AthleteClubAthlete = {
    /**
     * Resource state, indicates level of detail. Possible values: 1 -> "meta", 2 -> "summary", 3 -> "detail"
     */
    resource_state?: number;
    /**
     * The athlete's first name.
     */
    firstname?: string;
    /**
     * The athlete's last initial.
     */
    lastname?: string;
    /**
     * The athlete's member status.
     */
    member?: string;
    /**
     * Whether the athlete is a club admin.
     */
    admin?: boolean;
    /**
     * Whether the athlete is club owner.
     */
    owner?: boolean;
};

export type AthleteDetailedAthlete = AthleteSummaryAthlete & {
    /**
     * The athlete's follower count.
     */
    follower_count?: number;
    /**
     * The athlete's friend count.
     */
    friend_count?: number;
    /**
     * The athlete's preferred unit system.
     */
    measurement_preference?: 'feet' | 'meters';
    /**
     * The athlete's FTP (Functional Threshold Power).
     */
    ftp?: number;
    /**
     * The athlete's weight.
     */
    weight?: number;
    /**
     * The athlete's clubs.
     */
    clubs?: Array<ClubSummaryClub>;
    /**
     * The athlete's bikes.
     */
    bikes?: Array<GearSummaryGear>;
    /**
     * The athlete's shoes.
     */
    shoes?: Array<GearSummaryGear>;
};

export type AthleteMetaAthlete = {
    /**
     * The unique identifier of the athlete
     */
    id?: number;
};

export type AthleteSummaryAthlete = AthleteMetaAthlete & {
    /**
     * Resource state, indicates level of detail. Possible values: 1 -> "meta", 2 -> "summary", 3 -> "detail"
     */
    resource_state?: number;
    /**
     * The athlete's first name.
     */
    firstname?: string;
    /**
     * The athlete's last name.
     */
    lastname?: string;
    /**
     * URL to a 62x62 pixel profile picture.
     */
    profile_medium?: string;
    /**
     * URL to a 124x124 pixel profile picture.
     */
    profile?: string;
    /**
     * The athlete's city.
     */
    city?: string;
    /**
     * The athlete's state or geographical region.
     */
    state?: string;
    /**
     * The athlete's country.
     */
    country?: string;
    /**
     * The athlete's sex.
     */
    sex?: 'M' | 'F';
    /**
     * Deprecated.  Use summit field instead. Whether the athlete has any Summit subscription.
     */
    premium?: boolean;
    /**
     * Whether the athlete has any Summit subscription.
     */
    summit?: boolean;
    /**
     * The time at which the athlete was created.
     */
    created_at?: string;
    /**
     * The time at which the athlete was last updated.
     */
    updated_at?: string;
};

export type ClubDetailedClub = ClubSummaryClub & {
    /**
     * The membership status of the logged-in athlete.
     */
    membership?: 'member' | 'pending';
    /**
     * Whether the currently logged-in athlete is an administrator of this club.
     */
    admin?: boolean;
    /**
     * Whether the currently logged-in athlete is the owner of this club.
     */
    owner?: boolean;
    /**
     * The number of athletes in the club that the logged-in athlete follows.
     */
    following_count?: number;
};

export type ClubMetaClub = {
    /**
     * The club's unique identifier.
     */
    id?: number;
    /**
     * Resource state, indicates level of detail. Possible values: 1 -> "meta", 2 -> "summary", 3 -> "detail"
     */
    resource_state?: number;
    /**
     * The club's name.
     */
    name?: string;
};

export type ClubSummaryClub = ClubMetaClub & {
    /**
     * URL to a 60x60 pixel profile picture.
     */
    profile_medium?: string;
    /**
     * URL to a ~1185x580 pixel cover photo.
     */
    cover_photo?: string;
    /**
     * URL to a ~360x176  pixel cover photo.
     */
    cover_photo_small?: string;
    /**
     * Deprecated. Prefer to use activity_types.
     */
    sport_type?: 'cycling' | 'running' | 'triathlon' | 'other';
    /**
     * The activity types that count for a club. This takes precedence over sport_type.
     */
    activity_types?: Array<ActivityTypeActivityType>;
    /**
     * The club's city.
     */
    city?: string;
    /**
     * The club's state or geographical region.
     */
    state?: string;
    /**
     * The club's country.
     */
    country?: string;
    /**
     * Whether the club is private.
     */
    private?: boolean;
    /**
     * The club's member count.
     */
    member_count?: number;
    /**
     * Whether the club is featured or not.
     */
    featured?: boolean;
    /**
     * Whether the club is verified or not.
     */
    verified?: boolean;
    /**
     * The club's vanity URL.
     */
    url?: string;
};

export type CommentComment = {
    /**
     * The unique identifier of this comment
     */
    id?: number;
    /**
     * The identifier of the activity this comment is related to
     */
    activity_id?: number;
    /**
     * The content of the comment
     */
    text?: string;
    athlete?: AthleteSummaryAthlete;
    /**
     * The time at which this comment was created.
     */
    created_at?: string;
};

export type FaultError = {
    /**
     * The code associated with this error.
     */
    code?: string;
    /**
     * The specific field or aspect of the resource associated with this error.
     */
    field?: string;
    /**
     * The type of resource associated with this error.
     */
    resource?: string;
};

/**
 * Encapsulates the errors that may be returned from the API.
 */
export type FaultFault = {
    /**
     * The set of specific errors associated with this fault, if any.
     */
    errors?: Array<FaultError>;
    /**
     * The message of the fault.
     */
    message?: string;
};

export type GearDetailedGear = GearSummaryGear & {
    /**
     * The gear's brand name.
     */
    brand_name?: string;
    /**
     * The gear's model name.
     */
    model_name?: string;
    /**
     * The gear's frame type (bike only).
     */
    frame_type?: number;
    /**
     * The gear's description.
     */
    description?: string;
};

export type GearSummaryGear = {
    /**
     * The gear's unique identifier.
     */
    id?: string;
    /**
     * Resource state, indicates level of detail. Possible values: 2 -> "summary", 3 -> "detail"
     */
    resource_state?: number;
    /**
     * Whether this gear's is the owner's default one.
     */
    primary?: boolean;
    /**
     * The gear's name.
     */
    name?: string;
    /**
     * The distance logged with this gear.
     */
    distance?: number;
};

export type LapLap = {
    /**
     * The unique identifier of this lap
     */
    id?: number;
    activity?: ActivityMetaActivity;
    athlete?: AthleteMetaAthlete;
    /**
     * The lap's average cadence
     */
    average_cadence?: number;
    /**
     * The lap's average speed
     */
    average_speed?: number;
    /**
     * The lap's distance, in meters
     */
    distance?: number;
    /**
     * The lap's elapsed time, in seconds
     */
    elapsed_time?: number;
    /**
     * The start index of this effort in its activity's stream
     */
    start_index?: number;
    /**
     * The end index of this effort in its activity's stream
     */
    end_index?: number;
    /**
     * The index of this lap in the activity it belongs to
     */
    lap_index?: number;
    /**
     * The maximum speed of this lat, in meters per second
     */
    max_speed?: number;
    /**
     * The lap's moving time, in seconds
     */
    moving_time?: number;
    /**
     * The name of the lap
     */
    name?: string;
    /**
     * The athlete's pace zone during this lap
     */
    pace_zone?: number;
    split?: number;
    /**
     * The time at which the lap was started.
     */
    start_date?: string;
    /**
     * The time at which the lap was started in the local timezone.
     */
    start_date_local?: string;
    /**
     * The elevation gain of this lap, in meters
     */
    total_elevation_gain?: number;
};

/**
 * A pair of latitude/longitude coordinates, represented as an array of 2 floating point numbers.
 */
export type LatlngLatLng = [
    number,
    number
];

export type MapPolylineMap = {
    /**
     * The identifier of the map
     */
    id?: string;
    /**
     * The polyline of the map, only returned on detailed representation of an object
     */
    polyline?: string;
    /**
     * The summary polyline of the map
     */
    summary_polyline?: string;
};

export type PhotoPhotosSummary = {
    /**
     * The number of photos
     */
    count?: number;
    primary?: {
        id?: number;
        source?: number;
        unique_id?: string;
        urls?: {
            [key: string]: string;
        };
    };
};

export type RouteRoute = {
    athlete?: AthleteSummaryAthlete;
    /**
     * The description of the route
     */
    description?: string;
    /**
     * The route's distance, in meters
     */
    distance?: number;
    /**
     * The route's elevation gain.
     */
    elevation_gain?: number;
    /**
     * The unique identifier of this route
     */
    id?: number;
    /**
     * The unique identifier of the route in string format
     */
    id_str?: string;
    map?: MapPolylineMap;
    /**
     * The name of this route
     */
    name?: string;
    /**
     * Whether this route is private
     */
    private?: boolean;
    /**
     * Whether this route is starred by the logged-in athlete
     */
    starred?: boolean;
    /**
     * An epoch timestamp of when the route was created
     */
    timestamp?: number;
    /**
     * This route's type (1 for ride, 2 for runs)
     */
    type?: number;
    /**
     * This route's sub-type (1 for road, 2 for mountain bike, 3 for cross, 4 for trail, 5 for mixed)
     */
    sub_type?: number;
    /**
     * The time at which the route was created
     */
    created_at?: string;
    /**
     * The time at which the route was last updated
     */
    updated_at?: string;
    /**
     * Estimated time in seconds for the authenticated athlete to complete route
     */
    estimated_moving_time?: number;
    /**
     * The segments traversed by this route
     */
    segments?: Array<SegmentSummarySegment>;
    /**
     * The custom waypoints along this route
     */
    waypoints?: Array<WaypointWaypoint>;
};

export type SegmentDetailedSegment = SegmentSummarySegment & {
    /**
     * The time at which the segment was created.
     */
    created_at?: string;
    /**
     * The time at which the segment was last updated.
     */
    updated_at?: string;
    /**
     * The segment's total elevation gain.
     */
    total_elevation_gain?: number;
    map?: MapPolylineMap;
    /**
     * The total number of efforts for this segment
     */
    effort_count?: number;
    /**
     * The number of unique athletes who have an effort for this segment
     */
    athlete_count?: number;
    /**
     * Whether this segment is considered hazardous
     */
    hazardous?: boolean;
    /**
     * The number of stars for this segment
     */
    star_count?: number;
};

export type SegmentExplorerResponse = {
    /**
     * The set of segments matching an explorer request
     */
    segments?: Array<SegmentExplorerSegment>;
};

export type SegmentExplorerSegment = {
    /**
     * The unique identifier of this segment
     */
    id?: number;
    /**
     * The name of this segment
     */
    name?: string;
    /**
     * The category of the climb [0, 5]. Higher is harder ie. 5 is Hors catégorie, 0 is uncategorized in climb_category. If climb_category = 5, climb_category_desc = HC. If climb_category = 2, climb_category_desc = 3.
     */
    climb_category?: number;
    /**
     * The description for the category of the climb
     */
    climb_category_desc?: 'NC' | '4' | '3' | '2' | '1' | 'HC';
    /**
     * The segment's average grade, in percents
     */
    avg_grade?: number;
    start_latlng?: LatlngLatLng;
    end_latlng?: LatlngLatLng;
    /**
     * The segments's evelation difference, in meters
     */
    elev_difference?: number;
    /**
     * The segment's distance, in meters
     */
    distance?: number;
    /**
     * The polyline of the segment
     */
    points?: string;
};

export type SegmentSummarySegment = {
    /**
     * The unique identifier of this segment
     */
    id?: number;
    /**
     * The name of this segment
     */
    name?: string;
    activity_type?: 'Ride' | 'Run';
    /**
     * The segment's distance, in meters
     */
    distance?: number;
    /**
     * The segment's average grade, in percents
     */
    average_grade?: number;
    /**
     * The segments's maximum grade, in percents
     */
    maximum_grade?: number;
    /**
     * The segments's highest elevation, in meters
     */
    elevation_high?: number;
    /**
     * The segments's lowest elevation, in meters
     */
    elevation_low?: number;
    start_latlng?: LatlngLatLng;
    end_latlng?: LatlngLatLng;
    /**
     * The category of the climb [0, 5]. Higher is harder ie. 5 is Hors catégorie, 0 is uncategorized in climb_category.
     */
    climb_category?: number;
    /**
     * The segments's city.
     */
    city?: string;
    /**
     * The segments's state or geographical region.
     */
    state?: string;
    /**
     * The segment's country.
     */
    country?: string;
    /**
     * Whether this segment is private.
     */
    private?: boolean;
    athlete_pr_effort?: SegmentEffortSummaryPrSegmentEffort;
    athlete_segment_stats?: SegmentEffortSummarySegmentEffort;
};

export type SegmentEffortDetailedSegmentEffort = SegmentEffortSummarySegmentEffort & {
    /**
     * The name of the segment on which this effort was performed
     */
    name?: string;
    activity?: ActivityMetaActivity;
    athlete?: AthleteMetaAthlete;
    /**
     * The effort's moving time
     */
    moving_time?: number;
    /**
     * The start index of this effort in its activity's stream
     */
    start_index?: number;
    /**
     * The end index of this effort in its activity's stream
     */
    end_index?: number;
    /**
     * The effort's average cadence
     */
    average_cadence?: number;
    /**
     * The average wattage of this effort
     */
    average_watts?: number;
    /**
     * For riding efforts, whether the wattage was reported by a dedicated recording device
     */
    device_watts?: boolean;
    /**
     * The heart heart rate of the athlete during this effort
     */
    average_heartrate?: number;
    /**
     * The maximum heart rate of the athlete during this effort
     */
    max_heartrate?: number;
    segment?: SegmentSummarySegment;
    /**
     * The rank of the effort on the global leaderboard if it belongs in the top 10 at the time of upload
     */
    kom_rank?: number;
    /**
     * The rank of the effort on the athlete's leaderboard if it belongs in the top 3 at the time of upload
     */
    pr_rank?: number;
    /**
     * Whether this effort should be hidden when viewed within an activity
     */
    hidden?: boolean;
};

export type SegmentEffortSummaryPrSegmentEffort = {
    /**
     * The unique identifier of the activity related to the PR effort.
     */
    pr_activity_id?: number;
    /**
     * The elapsed time ot the PR effort.
     */
    pr_elapsed_time?: number;
    /**
     * The time at which the PR effort was started.
     */
    pr_date?: string;
    /**
     * Number of efforts by the authenticated athlete on this segment.
     */
    effort_count?: number;
};

export type SegmentEffortSummarySegmentEffort = {
    /**
     * The unique identifier of this effort
     */
    id?: number;
    /**
     * The unique identifier of the activity related to this effort
     */
    activity_id?: number;
    /**
     * The effort's elapsed time
     */
    elapsed_time?: number;
    /**
     * The time at which the effort was started.
     */
    start_date?: string;
    /**
     * The time at which the effort was started in the local timezone.
     */
    start_date_local?: string;
    /**
     * The effort's distance in meters
     */
    distance?: number;
    /**
     * Whether this effort is the current best on the leaderboard
     */
    is_kom?: boolean;
};

export type SplitSplit = {
    /**
     * The average speed of this split, in meters per second
     */
    average_speed?: number;
    /**
     * The distance of this split, in meters
     */
    distance?: number;
    /**
     * The elapsed time of this split, in seconds
     */
    elapsed_time?: number;
    /**
     * The elevation difference of this split, in meters
     */
    elevation_difference?: number;
    /**
     * The pacing zone of this split
     */
    pace_zone?: number;
    /**
     * The moving time of this split, in seconds
     */
    moving_time?: number;
    /**
     * N/A
     */
    split?: number;
};

/**
 * An enumeration of the sport types an activity may have. Distinct from ActivityType in that it has new types (e.g. MountainBikeRide)
 */
export type SportTypeSportType = 'AlpineSki' | 'BackcountrySki' | 'Badminton' | 'Canoeing' | 'Crossfit' | 'EBikeRide' | 'Elliptical' | 'EMountainBikeRide' | 'Golf' | 'GravelRide' | 'Handcycle' | 'HighIntensityIntervalTraining' | 'Hike' | 'IceSkate' | 'InlineSkate' | 'Kayaking' | 'Kitesurf' | 'MountainBikeRide' | 'NordicSki' | 'Pickleball' | 'Pilates' | 'Racquetball' | 'Ride' | 'RockClimbing' | 'RollerSki' | 'Rowing' | 'Run' | 'Sail' | 'Skateboard' | 'Snowboard' | 'Snowshoe' | 'Soccer' | 'Squash' | 'StairStepper' | 'StandUpPaddling' | 'Surfing' | 'Swim' | 'TableTennis' | 'Tennis' | 'TrailRun' | 'Velomobile' | 'VirtualRide' | 'VirtualRow' | 'VirtualRun' | 'Walk' | 'WeightTraining' | 'Wheelchair' | 'Windsurf' | 'Workout' | 'Yoga';

export type StreamAltitudeStream = StreamBaseStream & {
    /**
     * The sequence of altitude values for this stream, in meters
     */
    data?: Array<number>;
};

export type StreamBaseStream = {
    /**
     * The number of data points in this stream
     */
    original_size?: number;
    /**
     * The level of detail (sampling) in which this stream was returned
     */
    resolution?: 'low' | 'medium' | 'high';
    /**
     * The base series used in the case the stream was downsampled
     */
    series_type?: 'distance' | 'time';
};

export type StreamCadenceStream = StreamBaseStream & {
    /**
     * The sequence of cadence values for this stream, in rotations per minute
     */
    data?: Array<number>;
};

export type StreamDistanceStream = StreamBaseStream & {
    /**
     * The sequence of distance values for this stream, in meters
     */
    data?: Array<number>;
};

export type StreamHeartrateStream = StreamBaseStream & {
    /**
     * The sequence of heart rate values for this stream, in beats per minute
     */
    data?: Array<number>;
};

export type StreamLatLngStream = StreamBaseStream & {
    /**
     * The sequence of lat/long values for this stream
     */
    data?: Array<LatlngLatLng>;
};

export type StreamMovingStream = StreamBaseStream & {
    /**
     * The sequence of moving values for this stream, as boolean values
     */
    data?: Array<boolean>;
};

export type StreamPowerStream = StreamBaseStream & {
    /**
     * The sequence of power values for this stream, in watts
     */
    data?: Array<number>;
};

export type StreamSmoothGradeStream = StreamBaseStream & {
    /**
     * The sequence of grade values for this stream, as percents of a grade
     */
    data?: Array<number>;
};

export type StreamSmoothVelocityStream = StreamBaseStream & {
    /**
     * The sequence of velocity values for this stream, in meters per second
     */
    data?: Array<number>;
};

export type StreamStreamSet = {
    time?: StreamTimeStream;
    distance?: StreamDistanceStream;
    latlng?: StreamLatLngStream;
    altitude?: StreamAltitudeStream;
    velocity_smooth?: StreamSmoothVelocityStream;
    heartrate?: StreamHeartrateStream;
    cadence?: StreamCadenceStream;
    watts?: StreamPowerStream;
    temp?: StreamTemperatureStream;
    moving?: StreamMovingStream;
    grade_smooth?: StreamSmoothGradeStream;
};

export type StreamTemperatureStream = StreamBaseStream & {
    /**
     * The sequence of temperature values for this stream, in celsius degrees
     */
    data?: Array<number>;
};

export type StreamTimeStream = StreamBaseStream & {
    /**
     * The sequence of time values for this stream, in seconds
     */
    data?: Array<number>;
};

export type UploadUpload = {
    /**
     * The unique identifier of the upload
     */
    id?: number;
    /**
     * The unique identifier of the upload in string format
     */
    id_str?: string;
    /**
     * The external identifier of the upload
     */
    external_id?: string;
    /**
     * The error associated with this upload
     */
    error?: string;
    /**
     * The status of this upload
     */
    status?: string;
    /**
     * The identifier of the activity this upload resulted into
     */
    activity_id?: number;
};

export type WaypointWaypoint = {
    latlng?: LatlngLatLng;
    target_latlng?: LatlngLatLng;
    /**
     * Categories that the waypoint belongs to
     */
    categories?: Array<string>;
    /**
     * A title for the waypoint
     */
    title?: string;
    /**
     * A description of the waypoint (optional)
     */
    description?: string;
    /**
     * The number meters along the route that the waypoint is located
     */
    distance_into_route?: number;
};

export type ZonesActivityZone = {
    score?: number;
    distribution_buckets?: ZonesTimedZoneDistribution;
    type?: 'heartrate' | 'power';
    sensor_based?: boolean;
    points?: number;
    custom_zones?: boolean;
    max?: number;
};

export type ZonesHeartRateZoneRanges = {
    /**
     * Whether the athlete has set their own custom heart rate zones
     */
    custom_zones?: boolean;
    zones?: ZonesZoneRanges;
};

export type ZonesPowerZoneRanges = {
    zones?: ZonesZoneRanges;
};

/**
 * Stores the exclusive ranges representing zones and the time spent in each.
 */
export type ZonesTimedZoneDistribution = Array<ZonesTimedZoneRange>;

/**
 * A union type representing the time spent in a given zone.
 */
export type ZonesTimedZoneRange = ZonesZoneRange & {
    /**
     * The number of seconds spent in this zone
     */
    time?: number;
};

export type ZonesZoneRange = {
    /**
     * The minimum value in the range.
     */
    min?: number;
    /**
     * The maximum value in the range.
     */
    max?: number;
};

export type ZonesZoneRanges = Array<ZonesZoneRange>;

export type ZonesZones = {
    heart_rate?: ZonesHeartRateZoneRanges;
    power?: ZonesPowerZoneRanges;
};

export type GetStatsData = {
    body?: never;
    path: {
        /**
         * The identifier of the athlete. Must match the authenticated athlete.
         */
        id: number;
    };
    query?: never;
    url: '/athletes/{id}/stats';
};

export type GetStatsErrors = {
    /**
     * Unexpected error.
     */
    default: FaultFault;
};

export type GetStatsError = GetStatsErrors[keyof GetStatsErrors];

export type GetStatsResponses = {
    /**
     * Activity stats of the athlete.
     */
    200: ActivityStatsActivityStats;
};

export type GetStatsResponse = GetStatsResponses[keyof GetStatsResponses];

export type GetLoggedInAthleteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/athlete';
};

export type GetLoggedInAthleteErrors = {
    /**
     * Unexpected error.
     */
    default: FaultFault;
};

export type GetLoggedInAthleteError = GetLoggedInAthleteErrors[keyof GetLoggedInAthleteErrors];

export type GetLoggedInAthleteResponses = {
    /**
     * Profile information for the authenticated athlete.
     */
    200: AthleteDetailedAthlete;
};

export type GetLoggedInAthleteResponse = GetLoggedInAthleteResponses[keyof GetLoggedInAthleteResponses];

export type UpdateLoggedInAthleteData = {
    body?: never;
    path: {
        /**
         * The weight of the athlete in kilograms.
         */
        weight: number;
    };
    query?: never;
    url: '/athlete';
};

export type UpdateLoggedInAthleteErrors = {
    /**
     * Unexpected error.
     */
    default: FaultFault;
};

export type UpdateLoggedInAthleteError = UpdateLoggedInAthleteErrors[keyof UpdateLoggedInAthleteErrors];

export type UpdateLoggedInAthleteResponses = {
    /**
     * Profile information for the authenticated athlete.
     */
    200: AthleteDetailedAthlete;
};

export type UpdateLoggedInAthleteResponse = UpdateLoggedInAthleteResponses[keyof UpdateLoggedInAthleteResponses];

export type GetLoggedInAthleteZonesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/athlete/zones';
};

export type GetLoggedInAthleteZonesErrors = {
    /**
     * Unexpected error.
     */
    default: FaultFault;
};

export type GetLoggedInAthleteZonesError = GetLoggedInAthleteZonesErrors[keyof GetLoggedInAthleteZonesErrors];

export type GetLoggedInAthleteZonesResponses = {
    /**
     * Heart rate and power zones.
     */
    200: ZonesZones;
};

export type GetLoggedInAthleteZonesResponse = GetLoggedInAthleteZonesResponses[keyof GetLoggedInAthleteZonesResponses];

export type GetSegmentByIdData = {
    body?: never;
    path: {
        /**
         * The identifier of the segment.
         */
        id: number;
    };
    query?: never;
    url: '/segments/{id}';
};

export type GetSegmentByIdErrors = {
    /**
     * Unexpected error.
     */
    default: FaultFault;
};

export type GetSegmentByIdError = GetSegmentByIdErrors[keyof GetSegmentByIdErrors];

export type GetSegmentByIdResponses = {
    /**
     * Representation of a segment.
     */
    200: SegmentDetailedSegment;
};

export type GetSegmentByIdResponse = GetSegmentByIdResponses[keyof GetSegmentByIdResponses];

export type GetLoggedInAthleteStarredSegmentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number. Defaults to 1.
         */
        page?: number;
        /**
         * Number of items per page. Defaults to 30.
         */
        per_page?: number;
    };
    url: '/segments/starred';
};

export type GetLoggedInAthleteStarredSegmentsErrors = {
    /**
     * Unexpected error.
     */
    default: FaultFault;
};

export type GetLoggedInAthleteStarredSegmentsError = GetLoggedInAthleteStarredSegmentsErrors[keyof GetLoggedInAthleteStarredSegmentsErrors];

export type GetLoggedInAthleteStarredSegmentsResponses = {
    /**
     * List of the authenticated athlete's starred segments.
     */
    200: Array<SegmentSummarySegment>;
};

export type GetLoggedInAthleteStarredSegmentsResponse = GetLoggedInAthleteStarredSegmentsResponses[keyof GetLoggedInAthleteStarredSegmentsResponses];

export type StarSegmentData = {
    body?: never;
    path: {
        /**
         * The identifier of the segment to star.
         */
        id: number;
    };
    query?: never;
    url: '/segments/{id}/starred';
};

export type StarSegmentErrors = {
    /**
     * Unexpected error.
     */
    default: FaultFault;
};

export type StarSegmentError = StarSegmentErrors[keyof StarSegmentErrors];

export type StarSegmentResponses = {
    /**
     * Representation of a segment.
     */
    200: SegmentDetailedSegment;
};

export type StarSegmentResponse = StarSegmentResponses[keyof StarSegmentResponses];

export type GetEffortsBySegmentIdData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The identifier of the segment.
         */
        segment_id: number;
        /**
         * ISO 8601 formatted date time.
         */
        start_date_local?: string;
        /**
         * ISO 8601 formatted date time.
         */
        end_date_local?: string;
        /**
         * Number of items per page. Defaults to 30.
         */
        per_page?: number;
    };
    url: '/segment_efforts';
};

export type GetEffortsBySegmentIdErrors = {
    /**
     * Unexpected error.
     */
    default: FaultFault;
};

export type GetEffortsBySegmentIdError = GetEffortsBySegmentIdErrors[keyof GetEffortsBySegmentIdErrors];

export type GetEffortsBySegmentIdResponses = {
    /**
     * List of segment efforts.
     */
    200: Array<SegmentEffortDetailedSegmentEffort>;
};

export type GetEffortsBySegmentIdResponse = GetEffortsBySegmentIdResponses[keyof GetEffortsBySegmentIdResponses];

export type ExploreSegmentsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The latitude and longitude for two points describing a rectangular boundary for the search: [southwest corner latitutde, southwest corner longitude, northeast corner latitude, northeast corner longitude]
         */
        bounds: [
            number,
            number,
            number,
            number
        ];
        /**
         * Desired activity type.
         */
        activity_type?: 'running' | 'riding';
        /**
         * The minimum climbing category.
         */
        min_cat?: number;
        /**
         * The maximum climbing category.
         */
        max_cat?: number;
    };
    url: '/segments/explore';
};

export type ExploreSegmentsErrors = {
    /**
     * Unexpected error.
     */
    default: FaultFault;
};

export type ExploreSegmentsError = ExploreSegmentsErrors[keyof ExploreSegmentsErrors];

export type ExploreSegmentsResponses = {
    /**
     * List of matching segments.
     */
    200: SegmentExplorerResponse;
};

export type ExploreSegmentsResponse = ExploreSegmentsResponses[keyof ExploreSegmentsResponses];

export type GetSegmentEffortByIdData = {
    body?: never;
    path: {
        /**
         * The identifier of the segment effort.
         */
        id: number;
    };
    query?: never;
    url: '/segment_efforts/{id}';
};

export type GetSegmentEffortByIdErrors = {
    /**
     * Unexpected error.
     */
    default: FaultFault;
};

export type GetSegmentEffortByIdError = GetSegmentEffortByIdErrors[keyof GetSegmentEffortByIdErrors];

export type GetSegmentEffortByIdResponses = {
    /**
     * Representation of a segment effort.
     */
    200: SegmentEffortDetailedSegmentEffort;
};

export type GetSegmentEffortByIdResponse = GetSegmentEffortByIdResponses[keyof GetSegmentEffortByIdResponses];

export type CreateActivityData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/activities';
};

export type CreateActivityErrors = {
    /**
     * Unexpected error.
     */
    default: FaultFault;
};

export type CreateActivityError = CreateActivityErrors[keyof CreateActivityErrors];

export type CreateActivityResponses = {
    /**
     * The activity's detailed representation.
     */
    201: ActivityDetailedActivity;
};

export type CreateActivityResponse = CreateActivityResponses[keyof CreateActivityResponses];

export type GetActivityByIdData = {
    body?: never;
    path: {
        /**
         * The identifier of the activity.
         */
        id: number;
    };
    query?: {
        /**
         * To include all segments efforts.
         */
        include_all_efforts?: boolean;
    };
    url: '/activities/{id}';
};

export type GetActivityByIdErrors = {
    /**
     * Unexpected error.
     */
    default: FaultFault;
};

export type GetActivityByIdError = GetActivityByIdErrors[keyof GetActivityByIdErrors];

export type GetActivityByIdResponses = {
    /**
     * The activity's detailed representation.
     */
    200: ActivityDetailedActivity;
};

export type GetActivityByIdResponse = GetActivityByIdResponses[keyof GetActivityByIdResponses];

export type UpdateActivityByIdData = {
    body?: never;
    path: {
        /**
         * The identifier of the activity.
         */
        id: number;
    };
    query?: never;
    url: '/activities/{id}';
};

export type UpdateActivityByIdErrors = {
    /**
     * Unexpected error.
     */
    default: FaultFault;
};

export type UpdateActivityByIdError = UpdateActivityByIdErrors[keyof UpdateActivityByIdErrors];

export type UpdateActivityByIdResponses = {
    /**
     * The activity's detailed representation.
     */
    200: ActivityDetailedActivity;
};

export type UpdateActivityByIdResponse = UpdateActivityByIdResponses[keyof UpdateActivityByIdResponses];

export type GetLoggedInAthleteActivitiesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * An epoch timestamp to use for filtering activities that have taken place before a certain time.
         */
        before?: number;
        /**
         * An epoch timestamp to use for filtering activities that have taken place after a certain time.
         */
        after?: number;
        /**
         * Page number. Defaults to 1.
         */
        page?: number;
        /**
         * Number of items per page. Defaults to 30.
         */
        per_page?: number;
    };
    url: '/athlete/activities';
};

export type GetLoggedInAthleteActivitiesErrors = {
    /**
     * Unexpected error.
     */
    default: FaultFault;
};

export type GetLoggedInAthleteActivitiesError = GetLoggedInAthleteActivitiesErrors[keyof GetLoggedInAthleteActivitiesErrors];

export type GetLoggedInAthleteActivitiesResponses = {
    /**
     * The authenticated athlete's activities
     */
    200: Array<ActivitySummaryActivity>;
};

export type GetLoggedInAthleteActivitiesResponse = GetLoggedInAthleteActivitiesResponses[keyof GetLoggedInAthleteActivitiesResponses];

export type GetLapsByActivityIdData = {
    body?: never;
    path: {
        /**
         * The identifier of the activity.
         */
        id: number;
    };
    query?: never;
    url: '/activities/{id}/laps';
};

export type GetLapsByActivityIdErrors = {
    /**
     * Unexpected error.
     */
    default: FaultFault;
};

export type GetLapsByActivityIdError = GetLapsByActivityIdErrors[keyof GetLapsByActivityIdErrors];

export type GetLapsByActivityIdResponses = {
    /**
     * Activity Laps.
     */
    200: Array<LapLap>;
};

export type GetLapsByActivityIdResponse = GetLapsByActivityIdResponses[keyof GetLapsByActivityIdResponses];

export type GetZonesByActivityIdData = {
    body?: never;
    path: {
        /**
         * The identifier of the activity.
         */
        id: number;
    };
    query?: never;
    url: '/activities/{id}/zones';
};

export type GetZonesByActivityIdErrors = {
    /**
     * Unexpected error.
     */
    default: FaultFault;
};

export type GetZonesByActivityIdError = GetZonesByActivityIdErrors[keyof GetZonesByActivityIdErrors];

export type GetZonesByActivityIdResponses = {
    /**
     * Activity Zones.
     */
    200: Array<ZonesActivityZone>;
};

export type GetZonesByActivityIdResponse = GetZonesByActivityIdResponses[keyof GetZonesByActivityIdResponses];

export type GetCommentsByActivityIdData = {
    body?: never;
    path: {
        /**
         * The identifier of the activity.
         */
        id: number;
    };
    query?: {
        /**
         * Deprecated. Prefer to use after_cursor.
         */
        page?: number;
        /**
         * Deprecated. Prefer to use page_size.
         */
        per_page?: number;
        /**
         * Number of items per page. Defaults to 30.
         */
        page_size?: number;
        /**
         * Cursor of the last item in the previous page of results, used to request the subsequent page of results.  When omitted, the first page of results is fetched.
         */
        after_cursor?: string;
    };
    url: '/activities/{id}/comments';
};

export type GetCommentsByActivityIdErrors = {
    /**
     * Unexpected error.
     */
    default: FaultFault;
};

export type GetCommentsByActivityIdError = GetCommentsByActivityIdErrors[keyof GetCommentsByActivityIdErrors];

export type GetCommentsByActivityIdResponses = {
    /**
     * Comments.
     */
    200: Array<CommentComment>;
};

export type GetCommentsByActivityIdResponse = GetCommentsByActivityIdResponses[keyof GetCommentsByActivityIdResponses];

export type GetKudoersByActivityIdData = {
    body?: never;
    path: {
        /**
         * The identifier of the activity.
         */
        id: number;
    };
    query?: {
        /**
         * Page number. Defaults to 1.
         */
        page?: number;
        /**
         * Number of items per page. Defaults to 30.
         */
        per_page?: number;
    };
    url: '/activities/{id}/kudos';
};

export type GetKudoersByActivityIdErrors = {
    /**
     * Unexpected error.
     */
    default: FaultFault;
};

export type GetKudoersByActivityIdError = GetKudoersByActivityIdErrors[keyof GetKudoersByActivityIdErrors];

export type GetKudoersByActivityIdResponses = {
    /**
     * Comments.
     */
    200: Array<AthleteSummaryAthlete>;
};

export type GetKudoersByActivityIdResponse = GetKudoersByActivityIdResponses[keyof GetKudoersByActivityIdResponses];

export type GetClubByIdData = {
    body?: never;
    path: {
        /**
         * The identifier of the club.
         */
        id: number;
    };
    query?: never;
    url: '/clubs/{id}';
};

export type GetClubByIdErrors = {
    /**
     * Unexpected error.
     */
    default: FaultFault;
};

export type GetClubByIdError = GetClubByIdErrors[keyof GetClubByIdErrors];

export type GetClubByIdResponses = {
    /**
     * The detailed representation of a club.
     */
    200: ClubDetailedClub;
};

export type GetClubByIdResponse = GetClubByIdResponses[keyof GetClubByIdResponses];

export type GetClubMembersByIdData = {
    body?: never;
    path: {
        /**
         * The identifier of the club.
         */
        id: number;
    };
    query?: {
        /**
         * Page number. Defaults to 1.
         */
        page?: number;
        /**
         * Number of items per page. Defaults to 30.
         */
        per_page?: number;
    };
    url: '/clubs/{id}/members';
};

export type GetClubMembersByIdErrors = {
    /**
     * Unexpected error.
     */
    default: FaultFault;
};

export type GetClubMembersByIdError = GetClubMembersByIdErrors[keyof GetClubMembersByIdErrors];

export type GetClubMembersByIdResponses = {
    /**
     * A list of club athlete representations.
     */
    200: Array<AthleteClubAthlete>;
};

export type GetClubMembersByIdResponse = GetClubMembersByIdResponses[keyof GetClubMembersByIdResponses];

export type GetClubAdminsByIdData = {
    body?: never;
    path: {
        /**
         * The identifier of the club.
         */
        id: number;
    };
    query?: {
        /**
         * Page number. Defaults to 1.
         */
        page?: number;
        /**
         * Number of items per page. Defaults to 30.
         */
        per_page?: number;
    };
    url: '/clubs/{id}/admins';
};

export type GetClubAdminsByIdErrors = {
    /**
     * Unexpected error.
     */
    default: FaultFault;
};

export type GetClubAdminsByIdError = GetClubAdminsByIdErrors[keyof GetClubAdminsByIdErrors];

export type GetClubAdminsByIdResponses = {
    /**
     * A list of summary athlete representations.
     */
    200: Array<AthleteSummaryAthlete>;
};

export type GetClubAdminsByIdResponse = GetClubAdminsByIdResponses[keyof GetClubAdminsByIdResponses];

export type GetClubActivitiesByIdData = {
    body?: never;
    path: {
        /**
         * The identifier of the club.
         */
        id: number;
    };
    query?: {
        /**
         * Page number. Defaults to 1.
         */
        page?: number;
        /**
         * Number of items per page. Defaults to 30.
         */
        per_page?: number;
    };
    url: '/clubs/{id}/activities';
};

export type GetClubActivitiesByIdErrors = {
    /**
     * Unexpected error.
     */
    default: FaultFault;
};

export type GetClubActivitiesByIdError = GetClubActivitiesByIdErrors[keyof GetClubActivitiesByIdErrors];

export type GetClubActivitiesByIdResponses = {
    /**
     * A list of activities.
     */
    200: Array<ActivityClubActivity>;
};

export type GetClubActivitiesByIdResponse = GetClubActivitiesByIdResponses[keyof GetClubActivitiesByIdResponses];

export type GetLoggedInAthleteClubsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number. Defaults to 1.
         */
        page?: number;
        /**
         * Number of items per page. Defaults to 30.
         */
        per_page?: number;
    };
    url: '/athlete/clubs';
};

export type GetLoggedInAthleteClubsErrors = {
    /**
     * Unexpected error.
     */
    default: FaultFault;
};

export type GetLoggedInAthleteClubsError = GetLoggedInAthleteClubsErrors[keyof GetLoggedInAthleteClubsErrors];

export type GetLoggedInAthleteClubsResponses = {
    /**
     * A list of summary club representations.
     */
    200: Array<ClubSummaryClub>;
};

export type GetLoggedInAthleteClubsResponse = GetLoggedInAthleteClubsResponses[keyof GetLoggedInAthleteClubsResponses];

export type GetGearByIdData = {
    body?: never;
    path: {
        /**
         * The identifier of the gear.
         */
        id: string;
    };
    query?: never;
    url: '/gear/{id}';
};

export type GetGearByIdErrors = {
    /**
     * Unexpected error.
     */
    default: FaultFault;
};

export type GetGearByIdError = GetGearByIdErrors[keyof GetGearByIdErrors];

export type GetGearByIdResponses = {
    /**
     * A representation of the gear.
     */
    200: GearDetailedGear;
};

export type GetGearByIdResponse = GetGearByIdResponses[keyof GetGearByIdResponses];

export type GetRouteByIdData = {
    body?: never;
    path: {
        /**
         * The identifier of the route.
         */
        id: number;
    };
    query?: never;
    url: '/routes/{id}';
};

export type GetRouteByIdErrors = {
    /**
     * Unexpected error.
     */
    default: FaultFault;
};

export type GetRouteByIdError = GetRouteByIdErrors[keyof GetRouteByIdErrors];

export type GetRouteByIdResponses = {
    /**
     * A representation of the route.
     */
    200: RouteRoute;
};

export type GetRouteByIdResponse = GetRouteByIdResponses[keyof GetRouteByIdResponses];

export type GetRoutesByAthleteIdData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number. Defaults to 1.
         */
        page?: number;
        /**
         * Number of items per page. Defaults to 30.
         */
        per_page?: number;
    };
    url: '/athletes/{id}/routes';
};

export type GetRoutesByAthleteIdErrors = {
    /**
     * Unexpected error.
     */
    default: FaultFault;
};

export type GetRoutesByAthleteIdError = GetRoutesByAthleteIdErrors[keyof GetRoutesByAthleteIdErrors];

export type GetRoutesByAthleteIdResponses = {
    /**
     * A representation of the route.
     */
    200: Array<RouteRoute>;
};

export type GetRoutesByAthleteIdResponse = GetRoutesByAthleteIdResponses[keyof GetRoutesByAthleteIdResponses];

export type GetRouteAsGpxData = {
    body?: never;
    path: {
        /**
         * The identifier of the route.
         */
        id: number;
    };
    query?: never;
    url: '/routes/{id}/export_gpx';
};

export type GetRouteAsGpxErrors = {
    /**
     * Unexpected error.
     */
    default: FaultFault;
};

export type GetRouteAsGpxError = GetRouteAsGpxErrors[keyof GetRouteAsGpxErrors];

export type GetRouteAsGpxResponses = {
    /**
     * A GPX file with the route.
     */
    200: unknown;
};

export type GetRouteAsTcxData = {
    body?: never;
    path: {
        /**
         * The identifier of the route.
         */
        id: number;
    };
    query?: never;
    url: '/routes/{id}/export_tcx';
};

export type GetRouteAsTcxErrors = {
    /**
     * Unexpected error.
     */
    default: FaultFault;
};

export type GetRouteAsTcxError = GetRouteAsTcxErrors[keyof GetRouteAsTcxErrors];

export type GetRouteAsTcxResponses = {
    /**
     * A TCX file with the route.
     */
    200: unknown;
};

export type CreateUploadData = {
    body?: {
        /**
         * The uploaded file.
         */
        file?: Blob | File;
        /**
         * The desired name of the resulting activity.
         */
        name?: string;
        /**
         * The desired description of the resulting activity.
         */
        description?: string;
        /**
         * Whether the resulting activity should be marked as having been performed on a trainer.
         */
        trainer?: string;
        /**
         * Whether the resulting activity should be tagged as a commute.
         */
        commute?: string;
        /**
         * The format of the uploaded file.
         */
        data_type?: 'fit' | 'fit.gz' | 'tcx' | 'tcx.gz' | 'gpx' | 'gpx.gz';
        /**
         * The desired external identifier of the resulting activity.
         */
        external_id?: string;
    };
    path?: never;
    query?: never;
    url: '/uploads';
};

export type CreateUploadErrors = {
    /**
     * Unexpected error.
     */
    default: FaultFault;
};

export type CreateUploadError = CreateUploadErrors[keyof CreateUploadErrors];

export type CreateUploadResponses = {
    /**
     * A representation of the created upload.
     */
    201: UploadUpload;
};

export type CreateUploadResponse = CreateUploadResponses[keyof CreateUploadResponses];

export type GetUploadByIdData = {
    body?: never;
    path: {
        /**
         * The identifier of the upload.
         */
        uploadId: number;
    };
    query?: never;
    url: '/uploads/{uploadId}';
};

export type GetUploadByIdErrors = {
    /**
     * Unexpected error.
     */
    default: FaultFault;
};

export type GetUploadByIdError = GetUploadByIdErrors[keyof GetUploadByIdErrors];

export type GetUploadByIdResponses = {
    /**
     * Representation of the upload.
     */
    200: UploadUpload;
};

export type GetUploadByIdResponse = GetUploadByIdResponses[keyof GetUploadByIdResponses];

export type GetActivityStreamsData = {
    body?: never;
    path: {
        /**
         * The identifier of the activity.
         */
        id: number;
    };
    query: {
        /**
         * Desired stream types.
         */
        keys: Array<'time' | 'distance' | 'latlng' | 'altitude' | 'velocity_smooth' | 'heartrate' | 'cadence' | 'watts' | 'temp' | 'moving' | 'grade_smooth'>;
        /**
         * Must be true.
         */
        key_by_type: boolean;
    };
    url: '/activities/{id}/streams';
};

export type GetActivityStreamsErrors = {
    /**
     * Unexpected error.
     */
    default: FaultFault;
};

export type GetActivityStreamsError = GetActivityStreamsErrors[keyof GetActivityStreamsErrors];

export type GetActivityStreamsResponses = {
    /**
     * The set of requested streams.
     */
    200: StreamStreamSet;
};

export type GetActivityStreamsResponse = GetActivityStreamsResponses[keyof GetActivityStreamsResponses];

export type GetSegmentEffortStreamsData = {
    body?: never;
    path: {
        /**
         * The identifier of the segment effort.
         */
        id: number;
    };
    query: {
        /**
         * The types of streams to return.
         */
        keys: Array<'time' | 'distance' | 'latlng' | 'altitude' | 'velocity_smooth' | 'heartrate' | 'cadence' | 'watts' | 'temp' | 'moving' | 'grade_smooth'>;
        /**
         * Must be true.
         */
        key_by_type: boolean;
    };
    url: '/segment_efforts/{id}/streams';
};

export type GetSegmentEffortStreamsErrors = {
    /**
     * Unexpected error.
     */
    default: FaultFault;
};

export type GetSegmentEffortStreamsError = GetSegmentEffortStreamsErrors[keyof GetSegmentEffortStreamsErrors];

export type GetSegmentEffortStreamsResponses = {
    /**
     * The set of requested streams.
     */
    200: StreamStreamSet;
};

export type GetSegmentEffortStreamsResponse = GetSegmentEffortStreamsResponses[keyof GetSegmentEffortStreamsResponses];

export type GetSegmentStreamsData = {
    body?: never;
    path: {
        /**
         * The identifier of the segment.
         */
        id: number;
    };
    query: {
        /**
         * The types of streams to return.
         */
        keys: Array<'distance' | 'latlng' | 'altitude'>;
        /**
         * Must be true.
         */
        key_by_type: boolean;
    };
    url: '/segments/{id}/streams';
};

export type GetSegmentStreamsErrors = {
    /**
     * Unexpected error.
     */
    default: FaultFault;
};

export type GetSegmentStreamsError = GetSegmentStreamsErrors[keyof GetSegmentStreamsErrors];

export type GetSegmentStreamsResponses = {
    /**
     * The set of requested streams.
     */
    200: StreamStreamSet;
};

export type GetSegmentStreamsResponse = GetSegmentStreamsResponses[keyof GetSegmentStreamsResponses];

export type GetRouteStreamsData = {
    body?: never;
    path: {
        /**
         * The identifier of the route.
         */
        id: number;
    };
    query?: never;
    url: '/routes/{id}/streams';
};

export type GetRouteStreamsErrors = {
    /**
     * Unexpected error.
     */
    default: FaultFault;
};

export type GetRouteStreamsError = GetRouteStreamsErrors[keyof GetRouteStreamsErrors];

export type GetRouteStreamsResponses = {
    /**
     * The set of requested streams.
     */
    200: StreamStreamSet;
};

export type GetRouteStreamsResponse = GetRouteStreamsResponses[keyof GetRouteStreamsResponses];

export type ClientOptions = {
    baseUrl: 'https://www.strava.com/api/v3' | (string & {});
};
