import type { DetailedActivity } from "strava-v3";

export type SportType = DetailedActivity["sport_type"];

export const sportTypeTitles: Record<SportType, string> = {
  AlpineSki: "Alpine ski",
  BackcountrySki: "Backcountry ski",
  Canoeing: "Canoeing",
  Crossfit: "CrossFit",
  EBikeRide: "E-bike ride",
  Elliptical: "Elliptical",
  EMountainBikeRide: "E‑mountain bike ride",
  Golf: "Golf",
  GravelRide: "Gravel ride",
  Handcycle: "Handcycle",
  Hike: "Hike",
  IceSkate: "Ice skate",
  InlineSkate: "Inline skate",
  Kayaking: "Kayaking",
  Kitesurf: "Kitesurf",
  MountainBikeRide: "Mountain bike ride",
  NordicSki: "Nordic ski",
  Ride: "Bike ride",
  RockClimbing: "Rock climbing",
  RollerSki: "Roller ski",
  Rowing: "Rowing",
  Run: "Run",
  Sail: "Sail",
  Skateboard: "Skateboard",
  Snowboard: "Snowboard",
  Snowshoe: "Snowshoe",
  Soccer: "Soccer",
  StairStepper: "Stair stepper",
  StandUpPaddling: "Stand up paddling",
  Surfing: "Surfing",
  Swim: "Swim",
  TrailRun: "Trail run",
  Velomobile: "Velomobile",
  VirtualRide: "Virtual ride",
  VirtualRun: "Virtual run",
  Walk: "Walk",
  WeightTraining: "Weight training",
  Wheelchair: "Wheelchair",
  Windsurf: "Windsurf",
  Workout: "Workout",
  Yoga: "Yoga",
  Badminton: "Badminton",
  HighIntensityIntervalTraining: "HIIT",
  Pickleball: "Pickleball",
  Pilates: "Pilates",
  Racquetball: "Racquetball",
  Squash: "Squash",
  TableTennis: "Table tennis",
  Tennis: "Tennis",
  VirtualRow: "Virtual row",
};
